
jwt:
  header: Authorization
  #HS512 \uC54C\uACE0\uB9AC\uC998\uC744 \uC0AC\uC6A9\uD560 \uAC83\uC774\uAE30 \uB54C\uBB38\uC5D0 512bit, \uC989 64byte \uC774\uC0C1\uC758 secret key\uB97C \uC0AC\uC6A9\uD574\uC57C \uD55C\uB2E4.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
