#spring.datasource.url=jdbc:h2:tcp://localhost/~/shop
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=1
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none

spring:
  h2:
    console:
      enabled:true


  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    driver-class-name: org.h2.Driver
    username: sa
    password: 1


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#logback \uC0AC\uC6A9
logging:
  level:
    com.sideproject: debug

